### ISSUE TITLE
Batched Buffer broken

### ISSUE THREAD

**Issue by mhubii** [ros-ai/ros2_whisper#15]
The `BatchedBuffer` can lead to

- Uninferenced code
- Shorter than target batch

https://github.com/ros-ai/ros2_whisper/blob/d1741e656a82aa77b2f9a883fda9aa332d4aa00a/whisper_util/include/whisper_util/audio_buffers.hpp#L62

**Comment by NathanCorral** [comment]
Hey @mhubii,

I'm currently working on a modification to buffering and adding in a constant publisher for the audio transcript, as mentioned in [issue #12](https://github.com/ros-ai/ros2_whisper/issues/12).

It's still a work in progress, and you can check out my fork [here](https://github.com/NathanCorral/ros2_whisper/tree/dev-publisher-buffer).

I just wanted to avoid overlapping efforts, so I thought I'd reach out. Let me know if you'd like me to submit a pull request when it's ready.

**Comment by mhubii** [comment]
Hey @NathanCorral , sounds great, please do create a PR. Happy to review and merge !

**Comment by mhubii** [comment]
think this can be closed following #18
